development:
  adapter: postgresql
  encoding: unicode
  database: learning_platform_development
  pool: 5
  timeout: 5000
  username: emkey
  password:
  
test:
  adapter: postgresql
  encoding: unicode
  database: learning_platform_test
  pool: 5
  timeout: 5000
  username: emkey
  password: